#!/bin/bash

echo "请输入初始端口 x："
read x

echo "请输入末尾端口 y："
read y

echo
echo
while [ $x -le $y ]
do
    echo "x = $x" 
    cmd="curl localhost:$x/stake"
    echo "执行命令：$cmd" 
    sleep 10 
    x=$((x + 3))
    result=$(eval $cmd) 

done 
echo "质押查询完成"
