#!/bin/bash

echo "Please input start port x："
read x

echo "Please input end port y："
read y

echo
echo
while [ $x -le $y ]
do
    echo "x = $x" 
    cmd="curl localhost:$x/stake"
    echo "Execute command：$cmd" 
    sleep 10 
    x=$((x + 3))
    result=$(eval $cmd) 

done 
echo "Stake search complete"
