#!/bin/bash

echo "Please input start port x："
read x

echo "Please input end port y："
read y

output_file="syncresults.txt"

> syncresults.txt

echo
echo
while [ $x -le $y ]
do
    echo "x = $x" > /dev/null
    cmd="sudo  curl -s -X GET http://localhost:$x/redistributionstate | jq"
    echo "Execute command：$cmd" > /dev/null
    result=$(eval $cmd) > /dev/null
    isFullySynced=$(echo "$result" | grep -o '"isFullySynced": *[^,}]*' | awk '{print $2}')
    if [ "$isFullySynced" = "true" ]
    then
        echo "$x sync complete" >> "$output_file"
    else
        echo "$x sync not complete" >> "$output_file"
    fi
    x=$((x+3))
done > "$output_file" 2>&1
echo "sync search complete"
